name: Pull Request Analysis

on:
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Realizando análisis de SAST
      run: echo "Realizando análisis de SAST"

    - name: Comprobar requisitos
      id: check
      run: |
        if [ -f "allow_pull_request.txt" ]; then
          echo "::set-output name=allow_pull::true"
        else
          echo "::set-output name=allow_pull::false"
        fi

    - name: Permitiendo Pull Request
      if: steps.check.outputs.allow_pull == 'true'
      run: echo "Permitiendo Pull Request"

    - name: Impedir Pull Request
      if: steps.check.outputs.allow_pull == 'false'
      run: |
        echo "Build fallida. Impidiendo Pull Request"
        exit 1
